apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-01
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
data:
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  message: "Hello from ConfigMap!"
---  
apiVersion: batch/v1
kind: Job
metadata:
  name: delay-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wait
          image: busybox001
          command: ["sh", "-c", "sleep 60"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-02
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
data:
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  message: "Hello from ConfigMap!"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delay-job-04
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wait
          image: busybox0001
          command: ["sh", "-c", "sleep 60"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-05
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"  
data:
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  message: "Hello from ConfigMap!"
