apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  labels:
    app: hello-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
        argocd.argoproj.io/sync-wave: "10"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: hello-job
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: busybox:1.36
          command: ["sh", "-c", "echo 'Hello from Kubernetes Job via Argo CD'; sleep 10"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-01
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  message: "Hello from ConfigMap!!"
