apiVersion: batch/v1
kind: Job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
metadata:
  name: hello-job
  labels:
    app: hello-job
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: hello-job
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: busybox:1.36
          command: ["sh", "-c", "echo 'Hello from Kubernetes Job via Argo CD'; sleep 10"]

